Description: Test fit with the Pavia 17 parameterisation. NLL.
Minimiser: none
Seed: '1234'
qToQmax: '0.2'
Percentile cut: '5'
t0prescription: true
Paramfluct: false
Parameterisation: PV17
Parameters:
- {name: g2, starting_value: 0.128, step: 0.001, fix: false}         #, lower_bound: 0, upper_bound: 10}
- {name: N1, starting_value: 0.285, step: 0.003, fix: false}         #, lower_bound: 0, upper_bound: 10}
- {name: alpha, starting_value: 2.98, step: 0.030, fix: false}       #, lower_bound: 0, upper_bound: 10}
- {name: sigma, starting_value: 0.173, step: 0.002, fix: false}      #, lower_bound: 0, upper_bound: 10}
- {name: lambda, starting_value: 0.39, step: 0.005, fix: true}       #, lower_bound: 0, upper_bound: 10}
- {name: N3, starting_value: 0.212, step: 0.002, fix: true}          #, lower_bound: 0, upper_bound: 10}
- {name: beta, starting_value: 2.10, step: 0.02, fix: true}          #, lower_bound: 0, upper_bound: 10}
- {name: delta, starting_value: 0.094, step: 0.02, fix: true}        #, lower_bound: 0, upper_bound: 10}
- {name: gamma, starting_value: 2.52, step: 0.001, fix: true}        #, lower_bound: 0, upper_bound: 10}
- {name: lambdaF, starting_value: 5.29, step: 0.05, fix: true}       #, lower_bound: 0, upper_bound: 10}
- {name: N4, starting_value: 0.033, step: 0.001, fix: true}          #, lower_bound: 0, upper_bound: 10}
t0parameters: [0.128, 0.285, 2.98, 0.173, 0.39, 0.212, 2.10, 0.094, 2.52, 5.29, 0.033]
